import { ConfigParams } from 'hyperformula';

export const excelCompatibleConfig: Partial<ConfigParams> = {
  licenseKey: 'gpl-v3',
  evaluateNullToZero: true,
  leapYear1900: true,
  dateFormats: ['MM/DD/YYYY', 'MM/DD/YY', 'YYYY/MM/DD'],
  timeFormats: ['hh:mm', 'hh:mm:ss.sss'],
  currencySymbol: ['$', 'USD'],
  localeLang: 'en-US',
  functionArgSeparator: ',',
  decimalSeparator: '.',
  thousandSeparator: '', 
  arrayColumnSeparator: ',', 
  arrayRowSeparator: ';', 
  nullYear: 30, 
  caseSensitive: false, 
  accentSensitive: true,
  ignorePunctuation: false, 
  useWildcards: true, 
  useRegularExpressions: false, 
  matchWholeCell: true, 
  useArrayArithmetic: true,
  ignoreWhiteSpace: 'any',
  nullDate: { year: 1899, month: 12, day: 31 },
  smartRounding: true, 
};
